# -*- coding: utf-8 -*-
"""VerificAi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1szP7Pz7bf8fhvtvhmlW_4OX0_xbsaR7b

# 🔎 VerificAI - Uma IA de suporte e análise de currículos!

## Instalações, importações e requisições necessárias para a execução correta do programa.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip -q install google-generativeai
# %pip -q install google-adk
!pip install PyPDF2

import os
import sys
from google.colab import files, userdata
import PyPDF2
from google import genai
from IPython.display import display, Markdown
from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.tools import google_search
from google.genai import types
from datetime import date
import textwrap

os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY")

"""Conexão agente - parâmetro"""

def call_agent(agent: Agent, message_text: str) -> str:
    session_service = InMemorySessionService()
    session = session_service.create_session(app_name=agent.name, user_id="user1", session_id="session1")
    runner = Runner(agent=agent, app_name=agent.name, session_service=session_service)
    content = types.Content(role="user", parts=[types.Part(text=message_text)])
    final_response = ""
    for event in runner.run(user_id="user1", session_id="session1", new_message=content):
        if event.is_final_response():
            for part in event.content.parts:
                if part.text:
                    final_response += part.text + "\n"
    return final_response.strip()

def to_markdown(text):
    text = text.replace('•', '  *')
    return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

"""Definições dos agentes e suas respectivas *características*"""

def agente_avaliador(curriculo_extraido: str):
    avaliador = Agent(
        name="agente_avaliador",
        model="gemini-2.0-flash",
        instruction="""
        Você é um especialista sênior em Recursos Humanos, com vasta experiência em avaliação de currículos.
        Sua tarefa é analisar o conteúdo abaixo de forma crítica e construtiva.

        Siga as diretrizes a seguir:

        1. Identifique e destaque os principais pontos fortes do candidato, incluindo habilidades técnicas, experiências relevantes e conquistas notáveis.
        2. Aponte de forma clara e respeitosa os aspectos que podem ser aprimorados, como organização, clareza, formatação, uso de palavras-chave ou linguagem profissional.
        3. Mantenha uma abordagem objetiva, profissional e direta. Não há necessidade de cumprimento.

        Evite generalizações. Foque em observações específicas e úteis que realmente possam ajudar o candidato a melhorar seu currículo.
        """,
        description="Agente que avalia currículos criticamente."
    )
    entrada = f"Currículo:\n{curriculo_extraido}"
    return call_agent(avaliador, entrada)

def agente_otimizador(curriculo_extraido: str):
    otimizador = Agent(
        name="agente_otimizador",
        model="gemini-2.0-flash",
        instruction="""
        Você é um especialista em revisão e otimização de currículos, com ampla experiência em Recursos Humanos e comunicação profissional.

        Revise o conteúdo abaixo com o objetivo de torná-lo mais claro, direto e impactante. Faça os seguintes ajustes:
        - Corrija erros gramaticais, ortográficos e de pontuação.
        - Reescreva trechos confusos ou ambíguos, aprimorando a fluidez do texto.
        - Adote uma linguagem profissional e assertiva, adequada ao contexto de um currículo competitivo.
        - Mantenha as informações relevantes, destacando conquistas, competências e experiências de forma estratégica.

        O texto resultante deve transmitir profissionalismo, credibilidade e destacar o potencial do candidato.
        """,
        description="Agente otimizador de currículo"
    )
    entrada = f"Currículo:\n{curriculo_extraido}"
    return call_agent(otimizador, entrada)

def agente_carta(curriculo_otimizado: str):
    redator = Agent(
        name="agente_carta",
        model="gemini-2.0-flash",
        instruction="""
        Você é um redator profissional especializado na criação de cartas de apresentação impactantes e bem estruturadas.

        Com base no currículo fornecido, redija uma carta de apresentação em português com linguagem formal e objetiva. Destaque os principais pontos fortes do candidato, como experiências relevantes, habilidades técnicas e comportamentais, conquistas e diferenciais que o tornem atrativo para o mercado de trabalho.

        Adapte o tom para ser compatível com o perfil do profissional (júnior, pleno ou sênior) e enfatize como ele pode contribuir para a empresa ou vaga desejada.

        A carta deve transmitir confiança, profissionalismo e clareza, com uma estrutura lógica e persuasiva.
        """,
        description="Agente que gera carta de apresentação"
    )
    entrada = f"Currículo:\n{curriculo_otimizado}"
    return call_agent(redator, entrada)

def agente_recomendador(curriculo_otimizado: str):
    recomendador = Agent(
        name="agente_recomendador",
        model="gemini-2.0-flash",
        instruction="""
        Você é um mentor de carreira experiente, especializado em orientar profissionais em busca de crescimento e evolução.

        Com base no currículo apresentado, analise o perfil do candidato e forneça recomendações personalizadas para os próximos passos no desenvolvimento profissional, incluindo:

        - Habilidades técnicas e comportamentais que devem ser aprimoradas ou adquiridas.
        - Ferramentas, softwares ou metodologias relevantes que o candidato deve aprender para se destacar na área.
        - Tipos de projetos ou experiências práticas que podem fortalecer o currículo.
        - Recursos úteis para o aprendizado contínuo, como cursos (gratuitos ou pagos), livros, sites, comunidades ou certificações reconhecidas.

        Seja estratégico, direto e contextualize as sugestões com base no nível atual do candidato, sempre visando um avanço real e aplicável no mercado de trabalho.
        """,
        description="Agente de carreira para próximos passos"
    )
    entrada = f"Currículo:\n{curriculo_otimizado}"
    return call_agent(recomendador, entrada)

"""Execução principal"""

uploaded = files.upload()
file_name = list(uploaded.keys())[0]

if not file_name.lower().endswith(".pdf"):
    display(Markdown("⚠️ **O arquivo enviado não é um PDF. Por favor, envie um arquivo com extensão `.pdf`.**"))
    sys.exit()

try:
    with open(file_name, 'rb') as pdf:
        reader = PyPDF2.PdfReader(pdf)
        curriculo_extraido = "\n".join([page.extract_text() or "" for page in reader.pages])
except Exception as e:
    display(Markdown(f"❌ **Erro ao ler o arquivo PDF. Verifique se ele está corrompido ou é um PDF válido.**"))
    sys.exit()


print("🚀 Iniciando análise com os agentes da VerificAI...\n")

avaliacao = agente_avaliador(curriculo_extraido)
display(Markdown("## 📊 Avaliação Crítica"))
display(to_markdown(avaliacao))

otimizado = agente_otimizador(curriculo_extraido)
display(Markdown("## 📄 Currículo Otimizado"))
display(to_markdown(otimizado))

carta = agente_carta(otimizado)
display(Markdown("## ✉️ Carta de Apresentação"))
display(to_markdown(carta))

recomendacoes = agente_recomendador(otimizado)
display(Markdown("## 🧭 Próximos Passos"))
display(to_markdown(recomendacoes))

print("\n✅ Análise finalizada com sucesso!")