# -*- coding: utf-8 -*-
"""VerificAi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1szP7Pz7bf8fhvtvhmlW_4OX0_xbsaR7b

# 🔎 VerificAI - Uma IA de suporte e análise de currículos!

## Instalações, importações e requisições necessárias para a execução correta do programa.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip -q install google-generativeai
# %pip -q install google-adk
!pip install PyPDF2

import os
from google.colab import files, userdata
import PyPDF2
from google import genai
from IPython.display import display, Markdown
from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.tools import google_search
from google.genai import types
from datetime import date
import textwrap

os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY")

"""Conexão agente - parâmetro"""

def call_agent(agent: Agent, message_text: str) -> str:
    session_service = InMemorySessionService()
    session = session_service.create_session(app_name=agent.name, user_id="user1", session_id="session1")
    runner = Runner(agent=agent, app_name=agent.name, session_service=session_service)
    content = types.Content(role="user", parts=[types.Part(text=message_text)])
    final_response = ""
    for event in runner.run(user_id="user1", session_id="session1", new_message=content):
        if event.is_final_response():
            for part in event.content.parts:
                if part.text:
                    final_response += part.text + "\n"
    return final_response.strip()

def to_markdown(text):
    text = text.replace('•', '  *')
    return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

"""Definições dos agentes e suas respectivas *características*"""

def agente_avaliador(curriculo_extraido: str):
    avaliador = Agent(
        name="agente_avaliador",
        model="gemini-2.0-flash",
        instruction="""
        Você é um avaliador de currículos experiente, um especialista na área de recursos humanos. Avalie o conteúdo a seguir:
        Mantenha-se centrado nos pontos abaixo:
        1. Destaque pontos fortes.
        2. Aponte áreas de melhoria.
        3. Seja objetivo e profissional.
        """,
        description="Agente que avalia currículos criticamente."
    )
    entrada = f"Currículo:\n{curriculo_extraido}"
    return call_agent(avaliador, entrada)

def agente_otimizador(curriculo_extraido: str):
    otimizador = Agent(
        name="agente_otimizador",
        model="gemini-2.0-flash",
        instruction="""
        Você é um especialista em revisão de currículos. Melhore a clareza, objetividade e impacto do conteúdo abaixo.
        Corrija erros gramaticais e melhore a linguagem profissional.
        """,
        description="Agente otimizador de currículo"
    )
    entrada = f"Currículo:\n{curriculo_extraido}"
    return call_agent(otimizador, entrada)

def agente_carta(curriculo_otimizado: str):
    redator = Agent(
        name="agente_carta",
        model="gemini-2.0-flash",
        instruction="""
        Você é um redator especializado em cartas de apresentação. Escreva uma carta em português profissional
        com base no currículo abaixo, destacando os pontos fortes do candidato.
        """,
        description="Agente que gera carta de apresentação"
    )
    entrada = f"Currículo:\n{curriculo_otimizado}"
    return call_agent(redator, entrada)

def agente_recomendador(curriculo_otimizado: str):
    recomendador = Agent(
        name="agente_recomendador",
        model="gemini-2.0-flash",
        instruction="""
        Você é um mentor de carreira. Com base no currículo abaixo, recomende os próximos passos para o desenvolvimento profissional:
        - Habilidades a desenvolver
        - Ferramentas para aprender
        - Tipos de projeto para praticar
        - Recursos úteis (cursos, livros, etc)
        """,
        description="Agente de carreira para próximos passos"
    )
    entrada = f"Currículo:\n{curriculo_otimizado}"
    return call_agent(recomendador, entrada)

"""Execução principal"""

uploaded = files.upload()
file_name = list(uploaded.keys())[0]
pdf = open(file_name, 'rb')
reader = PyPDF2.PdfReader(pdf)
curriculo_extraido = "\n".join([page.extract_text() for page in reader.pages])
pdf.close()

print("🚀 Iniciando análise com os agentes da VerificAI...\n")

avaliacao = agente_avaliador(curriculo_extraido)
display(Markdown("## 📊 Avaliação Crítica"))
display(to_markdown(avaliacao))

otimizado = agente_otimizador(curriculo_extraido)
display(Markdown("## 📄 Currículo Otimizado"))
display(to_markdown(otimizado))

carta = agente_carta(otimizado)
display(Markdown("## ✉️ Carta de Apresentação"))
display(to_markdown(carta))

recomendacoes = agente_recomendador(otimizado)
display(Markdown("## 🧭 Próximos Passos"))
display(to_markdown(recomendacoes))

print("\n✅ Análise finalizada com sucesso!")